#!/usr/bin/env bash
#
#
#

sigterm_handler() {
    echo "I hate the kill command"
    delete_pid_file
    exit 1
}

sigint_handler() {
    echo "Y U no love me?!"
}

delete_pid_file() {
    rm -f /var/run/myscript.pid
    exit
}

trap 'sigterm_handler' SIGTERM
trap 'sigint_handler' SIGINT
trap 'delete_pid_file' SIGQUIT

echo $$ > /var/run/myscript.pid

while true
do
    echo "To infinity and beyond indefinitely"
    sleep 2
done
