#!/usr/bin/env bash
#prints best school if irter is not 8 or 4
#if iter is 4 prints bad luck
#if iter is 8 prints good luck

num=1
while [ $num -le 10 ]
do
	if [ $num -eq 4 ]
	then
		echo "bad luck"
	elif [ $num -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( num++ ))
done
