#!/usr/bin/env bash
#prints best school if irter is not 8 or 4
#if iter is 4 prints bad luck
#if iter is 8 prints good luck

num=1
while [ $num -le 20 ]
do
	echo "$num"
	case $num in 
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( num++ ))
done
