#!/usr/bin/env bash
#
#
#
#

fp="school"
if [ -e "$fp" ]
then
	echo "school file exists"
	if [ -s "$fp" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$fp" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
